app:
  appEnv: "dafault"
  serviceName: "touringparty"
  shutdownTimeout: 2
  shutdownDelay: 2
  gitCommitHash: "nil"
server:
  grpc:
    host: 0.0.0.0
    port: 9092
  http:
    host: 0.0.0.0
    port: 8080
tracing:
  serviceName: "touringparty"
  logSpans: false
  host: "localhost"
  port: "6831"
  disabled: false
sentry:
  appName: "touringparty"
  dsn: "dummy"
  mock: true
  errorLevel: 1